import { useEffect } from "react";
import {
  Box,
  Button,
  Container,
  Flex,
  Heading,
  SimpleGrid,
} from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";

import { useAppDispatch, useAppSelector } from "store/hook";
import { fetchMorePosts, fetchPosts } from "features/post/PostSlice";
import PostCard from "components/PostCard";
import DashboardLayout from "components/DashboardLayout";

export default function CategoryPost() {
  let dispatch = useAppDispatch();
  let router = useRouter();
  let categoryId = router.query.categoryId as string;
  const { page, nomore, posts, postsLoading, postsError } = useAppSelector(
    (state) => state.post
  );

  useEffect(() => {
    dispatch(fetchPosts({ page: 1, category: categoryId }));
  }, [dispatch, categoryId]);

  const loadMore = (e: React.MouseEvent<HTMLElement>) => {
    e.preventDefault();
    dispatch(fetchMorePosts({ page }));
  };

  return (
    <DashboardLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.xl" pb={10}>
        <Heading size="md">Category Post</Heading>
        {posts.length === 0 && <Box>Not any post yet.</Box>}
        <SimpleGrid columns={[1, 2, 2, 3]} spacing={5} my={2}>
          {posts &&
            posts.map((post) => {
              return <PostCard key={post._id} post={post} />;
            })}
        </SimpleGrid>
        <Flex justifyContent={"center"}>
          {!nomore && (
            <Button colorScheme="green" onClick={loadMore}>
              {postsLoading ? "Loading" : "Load More"}
            </Button>
          )}
        </Flex>
      </Container>
    </DashboardLayout>
  );
}
