import { useEffect } from "react";
import Head from "next/head";
import { useRouter } from "next/router";
import { Container, Heading, SimpleGrid } from "@chakra-ui/react";

import { useAppDispatch, useAppSelector } from "../store/hook";
import { fetchPosts } from "../features/post/PostSlice";
import PostCard from "components/PostCard";
import DashboardLayout from "components/DashboardLayout";

export default function PostPage() {
  let dispatch = useAppDispatch();
  const { posts } = useAppSelector((state) => state.post);
  useEffect(() => {
    dispatch(fetchPosts({ page: 1 }));
  }, [dispatch]);

  return (
    <DashboardLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.xl">
        <Heading size="md">Post</Heading>
        <SimpleGrid columns={[1, 2, 2, 3]} spacing={5} my={2}>
          {posts &&
            posts.map((post) => {
              return <PostCard key={post._id} post={post} />;
            })}
        </SimpleGrid>
      </Container>
    </DashboardLayout>
  );
}
