import { useEffect } from "react";
import {
  Box,
  Button,
  Container,
  Flex,
  Grid,
  Heading,
  SimpleGrid,
  Text,
  VStack,
} from "@chakra-ui/react";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";

import { useAppDispatch, useAppSelector } from "store/hook";
import { fetchMorePosts, fetchPost } from "features/post/PostSlice";
import DashboardLayout from "components/DashboardLayout";
import PostCard from "components/PostCard";

export default function SinglePost({}) {
  let dispatch = useAppDispatch();
  let router = useRouter();
  let slug = router.query.slug as string;
  const { post, posts, nomore, postsLoading, page } = useAppSelector(
    (state) => state.post
  );

  const loadMore = (e: React.MouseEvent<HTMLElement>) => {
    e.preventDefault();
    dispatch(fetchMorePosts({ page }));
  };

  useEffect(() => {
    dispatch(fetchPost(slug));
  }, [dispatch, slug]);

  return (
    <DashboardLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxW="container.xl">
        <Grid templateColumns={"3fr 1fr"} gap="4">
          <Box>
            <Heading size="lg">{post?.title}</Heading>
            <Flex alignItems={"center"}>
              <Button
                mr="2"
                size="sm"
                colorScheme="green"
                variant="ghost"
                bg="green.50"
              >
                Topic Name
              </Button>
              <Text> Posted on Nov 1</Text>
            </Flex>
            <Box position="relative">
              <Image src="/category.jpg" alt="post" layout="fill" />
            </Box>
            <Box my="4">{post?.description}</Box>

            <Box bg="gray.100" p={4} borderRadius={10}>
              <Heading size="md" fontWeight={500}>
                Share this story
              </Heading>
              <Flex>
                <Button variant={"ghost"}>Facebook</Button>
                <Button variant={"ghost"}>Twitter</Button>
                <Button variant={"ghost"}>Email</Button>
                <Button variant={"ghost"}>Copy Link</Button>
              </Flex>
            </Box>
          </Box>

          <VStack spacing="4">
            <Box bg="gray.100" width="100%" height="150px" borderRadius={10}>
              Ad 1
            </Box>
            <Box bg="gray.100" width="100%" height="150px" borderRadius={10}>
              Ad 2
            </Box>
            <Box bg="gray.100" width="100%" height="150px" borderRadius={10}>
              Ad 3
            </Box>
          </VStack>
        </Grid>
        <Box>
          <Heading size="md">Similar Posts</Heading>
          <SimpleGrid columns={[1, 2, 2, 3, 3]} spacing={5} my={2}>
            {posts.map((post) => {
              return <PostCard key={post._id} post={post} />;
            })}
          </SimpleGrid>
          <Flex justifyContent={"center"}>
            {!nomore && (
              <Button colorScheme="green" onClick={loadMore}>
                {postsLoading ? "Loading" : "Load More"}
              </Button>
            )}
          </Flex>
        </Box>
      </Container>
    </DashboardLayout>
  );
}
